export type AuditSignals = {
  pageTitleLength: number;
  metaDescriptionLength: number;
  headingCount: number;
  h1Count: number;
  linkCount: number;
  navItemCount: number;
  ctaCount: number;
  primaryCtaAboveFold: boolean;
  duplicatePrimaryCTA: boolean;
  formCount: number;
  inputCount: number;
  uploadInputCount: number;
  labelledInputs: number;
  placeholderOnlyInputs: number;
  hasSkipLink: boolean;
  imageCount: number;
  imageMissingAltCount: number;
  ariaLabelMissingOnIconButtons: number;
  interactiveWithoutFocusStyle: number;
  contrastRiskElements: number;
  averageFontSizePx: number;
  minFontSizePx: number;
  tapTargetSmallCount: number;
  mobileOverflowingElements: number;
  desktopToMobileElementDelta: number;
  inconsistentButtonStyles: boolean;
  hasLoadingIndicator: boolean;
  hasErrorStatePattern: boolean;
  hasSuccessStatePattern: boolean;
  emptyStateCount: number;
  heavyAboveFold: boolean;
  estimatedLcpMs: number;
  estimatedTtiMs: number;
  estimatedCls: number;
  policyLinkVisible: boolean;
  contactInfoVisible: boolean;
  socialProofCount: number;
  firstViewportTextDensity: number;
};

export function defaultSignals(): AuditSignals {
  return {
    pageTitleLength: 42,
    metaDescriptionLength: 110,
    headingCount: 7,
    h1Count: 1,
    linkCount: 18,
    navItemCount: 6,
    ctaCount: 2,
    primaryCtaAboveFold: true,
    duplicatePrimaryCTA: false,
    formCount: 1,
    inputCount: 4,
    uploadInputCount: 1,
    labelledInputs: 2,
    placeholderOnlyInputs: 2,
    hasSkipLink: false,
    imageCount: 9,
    imageMissingAltCount: 2,
    ariaLabelMissingOnIconButtons: 1,
    interactiveWithoutFocusStyle: 2,
    contrastRiskElements: 3,
    averageFontSizePx: 15.2,
    minFontSizePx: 12.5,
    tapTargetSmallCount: 2,
    mobileOverflowingElements: 1,
    desktopToMobileElementDelta: 16,
    inconsistentButtonStyles: true,
    hasLoadingIndicator: false,
    hasErrorStatePattern: false,
    hasSuccessStatePattern: false,
    emptyStateCount: 0,
    heavyAboveFold: true,
    estimatedLcpMs: 3200,
    estimatedTtiMs: 3800,
    estimatedCls: 0.19,
    policyLinkVisible: false,
    contactInfoVisible: false,
    socialProofCount: 1,
    firstViewportTextDensity: 0.18
  };
}
